services:
  zabbix-db:
    image: mariadb:11.4
    container_name: zabbix-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: zabbix_root_pass
      MARIADB_DATABASE: zabbix
      MARIADB_USER: zabbix
      MARIADB_PASSWORD: zabbix_pass
    volumes:
      - zabbix-db:/var/lib/mysql
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-7.4-latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      zabbix-db:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_DATABASE: zabbix
      ZBX_DEBUGLEVEL: 3
    volumes:
      - ./zabbix_server_alertscripts:/usr/lib/zabbix/alertscripts
    networks:
      - zabbix-net
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-7.4-latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      zabbix-server:
        condition: service_started
      zabbix-db:
        condition: service_healthy
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_DATABASE: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Europe/Moscow
    networks:
      - zabbix-net
    ports:
      - "8080:8080"


  nginx-custom:
    build: ./nginx-custom
    container_name: nginx-custom
    restart: unless-stopped
    networks:
      - zabbix-net
    ports:
      - "81:80"
    depends_on:
      - zabbix-server
    hostname: nginx-custom

  mysql-wp:
    # image: mariadb:11.4
    container_name: mysql-wp
    restart: unless-stopped
    build: ./mysql-wp
    environment:
      MARIADB_ROOT_PASSWORD: wp_root_pass
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wp_user
      MARIADB_PASSWORD: wp_pass
    volumes:
      - wp-mysql:/var/lib/mysql
    networks:
      - zabbix-net
    hostname: mysql-wp

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mysql-wp
    environment:
      WORDPRESS_DB_HOST: mysql-wp
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - zabbix-net
    ports:
      - "82:80"
    hostname: wordpress

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - zabbix-net
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.13.0
    container_name: kibana
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - zabbix-net
    ports:
      - "5601:5601"

  filebeat:
    image: elastic/filebeat:8.13.0
    container_name: filebeat
    restart: unless-stopped
    user: root
    depends_on:
      - elasticsearch
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge

volumes:
  zabbix-db:
  wp-mysql:
  es-data:
