[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0777

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:mariadb]
command=/usr/local/bin/docker-entrypoint.sh mariadbd
priority=10
autorestart=true
startsecs=5

[program:zabbix-agent2]
command=zabbix_agent2 -c /etc/zabbix/zabbix_agent2.conf
priority=20
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
