[supervisord]
nodaemon=true
user=root

[program:apache2]
command=/usr/local/bin/docker-entrypoint.sh apache2-foreground
environment=APACHE_RUN_USER=www-data,APACHE_RUN_GROUP=www-data
priority=10
autorestart=true
startsecs=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0

[program:zabbix-agent2]
command=zabbix_agent2 -c /etc/zabbix/zabbix_agent2.conf
priority=20
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
