[supervisord]
nodaemon=true

[program:nginx]
command=nginx -g 'daemon off;'
autorestart=true
priority=10

[program:zabbix-agent2]
command=zabbix_agent2 -c /etc/zabbix/zabbix_agent2.conf
autorestart=true
priority=20
